# Generated by Django 5.2.1 on 2025-05-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('interval', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('max_size', models.CharField(blank=True, help_text='e.g., 100M, 1G. Leave blank if no size limit.', max_length=10, null=True)),
                ('keep_rotations', models.PositiveIntegerField(default=7, help_text='Number of log rotations to keep.')),
            ],
        ),
        migrations.CreateModel(
            name='RsyslogHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Enter the IP address or hostname of the rsyslog host.', max_length=255, unique=True)),
            ],
        ),
    ]
