# Generated by Django 5.2.1 on 2025-06-22 10:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('unknown', 'Unknown Device'), ('fortigate', 'FortiGate Firewall'), ('paloalto', 'Palo Alto Firewall'), ('cisco', 'Cisco Device'), ('checkpoint', 'Check Point Firewall'), ('sophos', 'Sophos Firewall'), ('juniper', 'Juniper Device'), ('generic', 'Generic Syslog Device')], max_length=20)),
                ('description', models.TextField(help_text='Template description')),
                ('rsyslog_template', models.TextField(help_text='Rsyslog template definition')),
                ('parser_script', models.CharField(help_text='Python script for parsing (e.g., enhanced_fortigate_to_clickhouse.py)', max_length=255)),
                ('clickhouse_table', models.CharField(help_text='ClickHouse table name', max_length=100)),
                ('sample_log', models.TextField(blank=True, help_text='Sample log for testing')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parser_templates',
                'ordering': ['device_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this log source', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('ip_address', models.GenericIPAddressField(help_text='Source IP address', unique=True, validators=[django.core.validators.validate_ipv4_address])),
                ('hostname', models.CharField(blank=True, help_text='Detected hostname', max_length=255)),
                ('device_type', models.CharField(choices=[('unknown', 'Unknown Device'), ('fortigate', 'FortiGate Firewall'), ('paloalto', 'Palo Alto Firewall'), ('cisco', 'Cisco Device'), ('checkpoint', 'Check Point Firewall'), ('sophos', 'Sophos Firewall'), ('juniper', 'Juniper Device'), ('generic', 'Generic Syslog Device')], default='unknown', help_text='Type of device sending logs', max_length=20)),
                ('device_model', models.CharField(blank=True, help_text='Device model if detected', max_length=100)),
                ('device_version', models.CharField(blank=True, help_text='Device firmware/software version', max_length=50)),
                ('port', models.PositiveIntegerField(default=514, help_text='Port number for log reception')),
                ('protocol', models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP')], default='udp', help_text='Protocol used for log transmission', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='pending', help_text='Current status in approval workflow', max_length=10)),
                ('save_logs', models.BooleanField(default=True, help_text='Enable log file saving')),
                ('log_file_path', models.CharField(blank=True, help_text='Path where logs are saved', max_length=255)),
                ('log_template', models.CharField(choices=[('raw', 'Raw Logs'), ('timestamp', 'Timestamped'), ('detailed', 'Detailed Format'), ('fortigate_default', 'FortiGate Default'), ('paloalto_default', 'PaloAlto Default'), ('custom', 'Custom Template')], default='raw', help_text='Template used for log formatting', max_length=20)),
                ('custom_template', models.TextField(blank=True, help_text='Custom rsyslog template (when template=custom)')),
                ('parse_to_database', models.BooleanField(default=False, help_text='Enable parsing logs to ClickHouse database')),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='When first detected')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Last log received')),
                ('approved_by', models.CharField(blank=True, help_text='Who approved this source', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When approved', null=True)),
                ('rejected_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('total_logs', models.BigIntegerField(default=0, help_text='Total logs received')),
                ('logs_today', models.IntegerField(default=0, help_text='Logs received today')),
                ('logs_last_hour', models.IntegerField(default=0, help_text='Logs received in last hour')),
                ('configuration_data', models.JSONField(default=dict, help_text='Additional configuration data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'log_sources',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['ip_address'], name='log_sources_ip_addr_9beaa9_idx'), models.Index(fields=['status'], name='log_sources_status_68df33_idx'), models.Index(fields=['device_type'], name='log_sources_device__eb6bc2_idx'), models.Index(fields=['last_seen'], name='log_sources_last_se_8a65fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogSourceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('detected', 'Device Detected'), ('approved', 'Source Approved'), ('rejected', 'Source Rejected'), ('activated', 'Source Activated'), ('deactivated', 'Source Deactivated'), ('configured', 'Configuration Updated'), ('error', 'Error Occurred')], max_length=20)),
                ('description', models.TextField(help_text='Event description')),
                ('user', models.CharField(blank=True, help_text='User who triggered the event', max_length=100)),
                ('metadata', models.JSONField(default=dict, help_text='Additional event data')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.logsource')),
            ],
            options={
                'db_table': 'log_source_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['log_source', 'timestamp'], name='log_source__log_sou_3809b0_idx'), models.Index(fields=['event_type'], name='log_source__event_t_d7832b_idx')],
            },
        ),
    ]
