# Generated by Django 5.2.1 on 2025-05-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsysloghost',
            name='address',
            field=models.GenericIPAddressField(help_text='IP address allowed to send logs.', unique=True),
        ),
    ]
