# Generated by Django 5.2.1 on 2025-07-03 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Zone name (e.g., 'Internal', 'DMZ', 'External')", max_length=100)),
                ('zone_type', models.CharField(choices=[('internal', 'Internal Zone'), ('external', 'External Zone'), ('dmz', 'DMZ Zone'), ('management', 'Management Zone'), ('guest', 'Guest Zone'), ('trusted', 'Trusted Zone'), ('untrusted', 'Untrusted Zone'), ('vpn', 'VPN Zone'), ('custom', 'Custom Zone')], default='custom', help_text='Type of zone', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of the zone')),
                ('security_level', models.IntegerField(choices=[(0, 'Untrusted (0)'), (25, 'Low Security (25)'), (50, 'Medium Security (50)'), (75, 'High Security (75)'), (100, 'Maximum Security (100)')], default=50, help_text='Security level (0-100)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this zone active')),
                ('allow_inter_zone', models.BooleanField(default=True, help_text='Allow traffic between interfaces in this zone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(help_text='Device this zone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='dashboard.logsource')),
            ],
            options={
                'db_table': 'device_zones',
                'ordering': ['device', 'security_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSubnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Subnet name (e.g., 'Internal LAN', 'DMZ Servers')", max_length=100)),
                ('network_address', models.CharField(help_text="Network address with CIDR (e.g., '192.168.1.0/24')", max_length=18)),
                ('subnet_type', models.CharField(choices=[('management', 'Management Network'), ('user', 'User Network'), ('server', 'Server Network'), ('dmz', 'DMZ Network'), ('wan', 'WAN Network'), ('lan', 'LAN Network'), ('vlan', 'VLAN Network'), ('vpn', 'VPN Network'), ('custom', 'Custom Network')], default='custom', help_text='Type of subnet', max_length=20)),
                ('gateway', models.GenericIPAddressField(blank=True, help_text='Gateway IP address', null=True)),
                ('vlan_id', models.PositiveIntegerField(blank=True, help_text='VLAN ID (if applicable)', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the subnet')),
                ('is_active', models.BooleanField(default=True, help_text='Is this subnet active')),
                ('monitor_traffic', models.BooleanField(default=True, help_text='Monitor traffic for this subnet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(help_text='Device this subnet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='dashboard.logsource')),
                ('zone', models.ForeignKey(blank=True, help_text='Zone this subnet belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnets', to='dashboard.devicezone')),
            ],
            options={
                'db_table': 'device_subnets',
                'ordering': ['device', 'zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Interface name (e.g., 'eth0', 'GigabitEthernet0/1', 'ae1.100')", max_length=100)),
                ('alias', models.CharField(blank=True, help_text='Interface alias or description', max_length=100)),
                ('interface_type', models.CharField(choices=[('ethernet', 'Ethernet'), ('wifi', 'Wireless'), ('tunnel', 'Tunnel'), ('vlan', 'VLAN'), ('loopback', 'Loopback'), ('virtual', 'Virtual'), ('aggregate', 'Aggregate'), ('management', 'Management'), ('custom', 'Custom')], default='ethernet', help_text='Type of interface', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address assigned to interface', null=True)),
                ('subnet_mask', models.CharField(blank=True, help_text="Subnet mask (e.g., '255.255.255.0')", max_length=15)),
                ('cidr_prefix', models.PositiveIntegerField(blank=True, help_text='CIDR prefix length (e.g., 24 for /24)', null=True)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address (format: XX:XX:XX:XX:XX:XX)', max_length=17)),
                ('speed', models.CharField(choices=[('10', '10 Mbps'), ('100', '100 Mbps'), ('1000', '1 Gbps'), ('10000', '10 Gbps'), ('25000', '25 Gbps'), ('40000', '40 Gbps'), ('100000', '100 Gbps'), ('auto', 'Auto Negotiate')], default='auto', help_text='Interface speed', max_length=10)),
                ('duplex', models.CharField(choices=[('full', 'Full Duplex'), ('half', 'Half Duplex'), ('auto', 'Auto Negotiate')], default='auto', help_text='Duplex mode', max_length=10)),
                ('mtu', models.PositiveIntegerField(default=1500, help_text='Maximum Transmission Unit')),
                ('vlan_id', models.PositiveIntegerField(blank=True, help_text='VLAN ID (if interface is a VLAN)', null=True)),
                ('native_vlan', models.PositiveIntegerField(blank=True, help_text='Native VLAN ID for trunk interfaces', null=True)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('admin_down', 'Administratively Down'), ('unknown', 'Unknown')], default='unknown', help_text='Interface operational status', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this interface active')),
                ('is_management', models.BooleanField(default=False, help_text='Is this a management interface')),
                ('monitor_traffic', models.BooleanField(default=True, help_text='Monitor traffic on this interface')),
                ('description', models.TextField(blank=True, help_text='Optional description of the interface')),
                ('configuration_data', models.JSONField(default=dict, help_text='Additional interface configuration (routing, ACLs, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(help_text='Device this interface belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='dashboard.logsource')),
                ('subnets', models.ManyToManyField(blank=True, help_text='Subnets accessible through this interface', related_name='interfaces', to='dashboard.devicesubnet')),
                ('zone', models.ForeignKey(blank=True, help_text='Zone this interface belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfaces', to='dashboard.devicezone')),
            ],
            options={
                'db_table': 'device_interfaces',
                'ordering': ['device', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkTopologySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_data', models.JSONField(help_text='Complete network topology data (zones, subnets, interfaces)')),
                ('changes_detected', models.JSONField(default=list, help_text='List of changes from previous snapshot')),
                ('change_summary', models.TextField(blank=True, help_text='Human-readable summary of changes')),
                ('created_by', models.CharField(blank=True, help_text='User who created this snapshot', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(help_text='Device this snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='topology_snapshots', to='dashboard.logsource')),
            ],
            options={
                'db_table': 'network_topology_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='devicezone',
            index=models.Index(fields=['device', 'zone_type'], name='device_zone_device__099b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='devicezone',
            index=models.Index(fields=['device', 'is_active'], name='device_zone_device__b310a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicezone',
            unique_together={('device', 'name')},
        ),
        migrations.AddIndex(
            model_name='devicesubnet',
            index=models.Index(fields=['device', 'subnet_type'], name='device_subn_device__dab0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesubnet',
            index=models.Index(fields=['device', 'is_active'], name='device_subn_device__c90b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesubnet',
            index=models.Index(fields=['zone'], name='device_subn_zone_id_cf0986_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicesubnet',
            unique_together={('device', 'network_address')},
        ),
        migrations.AddIndex(
            model_name='deviceinterface',
            index=models.Index(fields=['device', 'interface_type'], name='device_inte_device__be17a2_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinterface',
            index=models.Index(fields=['device', 'is_active'], name='device_inte_device__7f5354_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinterface',
            index=models.Index(fields=['zone'], name='device_inte_zone_id_a1bc1a_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinterface',
            index=models.Index(fields=['ip_address'], name='device_inte_ip_addr_24827d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceinterface',
            unique_together={('device', 'name')},
        ),
        migrations.AddIndex(
            model_name='networktopologysnapshot',
            index=models.Index(fields=['device', 'created_at'], name='network_top_device__8ce5ae_idx'),
        ),
    ]
