# Generated by Django 5.2.1 on 2025-08-25 10:30

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0002_devicezone_devicesubnet_deviceinterface_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Role name', max_length=100, unique=True)),
                ('level', models.CharField(choices=[('viewer', 'Viewer'), ('analyst', 'Analyst'), ('admin', 'Administrator'), ('superuser', 'Super Administrator')], help_text='Role hierarchy level', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Role description')),
                ('can_view_logs', models.BooleanField(default=True, help_text='Can view firewall logs')),
                ('can_export_logs', models.BooleanField(default=False, help_text='Can export log data')),
                ('can_manage_devices', models.BooleanField(default=False, help_text='Can manage registered devices')),
                ('can_configure_sources', models.BooleanField(default=False, help_text='Can configure log sources')),
                ('can_view_analytics', models.BooleanField(default=True, help_text='Can view analytics dashboards')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Can manage user accounts')),
                ('can_view_audit', models.BooleanField(default=False, help_text='Can view audit logs')),
                ('can_system_config', models.BooleanField(default=False, help_text='Can modify system configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Is this role active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Django permissions for this role', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'auth_roles',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Username (3-150 characters)', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('full_name', models.CharField(blank=True, help_text='Full display name', max_length=255)),
                ('department', models.CharField(blank=True, help_text='Department or team', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('password_expires', models.DateTimeField(blank=True, help_text='When password expires (null = never)', null=True)),
                ('require_password_change', models.BooleanField(default=False, help_text='Force password change on next login')),
                ('account_locked', models.BooleanField(default=False, help_text='Account locked due to security policy')),
                ('account_locked_until', models.DateTimeField(blank=True, help_text='Account unlocked automatically after this time', null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed login attempts')),
                ('last_failed_login', models.DateTimeField(blank=True, help_text='Timestamp of last failed login attempt', null=True)),
                ('max_concurrent_sessions', models.PositiveIntegerField(default=3, help_text='Maximum number of concurrent sessions allowed')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=480, help_text='Session timeout in minutes')),
                ('allowed_ip_addresses', models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses (empty = no restrictions)')),
                ('last_password_change', models.DateTimeField(blank=True, help_text='When password was last changed', null=True)),
                ('last_activity', models.DateTimeField(blank=True, help_text='Last recorded activity', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, help_text="User's primary role", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Username at time of action (preserved if user deleted)', max_length=150)),
                ('action_type', models.CharField(choices=[('auth', 'Authentication'), ('user_mgmt', 'User Management'), ('role_mgmt', 'Role Management'), ('device_mgmt', 'Device Management'), ('log_access', 'Log Access'), ('log_export', 'Log Export'), ('config_change', 'Configuration Change'), ('system_access', 'System Access'), ('security', 'Security Event'), ('data_modify', 'Data Modification')], help_text='Type of action performed', max_length=20)),
                ('action', models.CharField(help_text='Specific action description', max_length=100)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('denied', 'Access Denied'), ('error', 'Error')], help_text='Action result', max_length=10)),
                ('resource_type', models.CharField(blank=True, help_text='Type of resource affected', max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='ID of resource affected', max_length=100)),
                ('resource_name', models.CharField(blank=True, help_text='Name of resource affected', max_length=255)),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address')),
                ('user_agent', models.TextField(help_text='Client user agent string')),
                ('session_key', models.CharField(blank=True, help_text='Session key if available', max_length=40)),
                ('method', models.CharField(blank=True, help_text='HTTP method', max_length=10)),
                ('path', models.CharField(blank=True, help_text='Request path', max_length=500)),
                ('details', models.JSONField(default=dict, help_text='Additional action details')),
                ('old_values', models.JSONField(default=dict, help_text='Previous values (for modifications)')),
                ('new_values', models.JSONField(default=dict, help_text='New values (for modifications)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When action occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='auth_audit__user_id_581b94_idx'), models.Index(fields=['action_type', 'timestamp'], name='auth_audit__action__d0877f_idx'), models.Index(fields=['result', 'timestamp'], name='auth_audit__result_cae02d_idx'), models.Index(fields=['ip_address', 'timestamp'], name='auth_audit__ip_addr_731146_idx'), models.Index(fields=['timestamp'], name='auth_audit__timesta_dd7267_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username attempted', max_length=150)),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address')),
                ('user_agent', models.TextField(help_text='Client user agent string')),
                ('attempt_type', models.CharField(choices=[('success', 'Successful Login'), ('failure', 'Failed Login'), ('blocked', 'Blocked Attempt')], help_text='Type of login attempt', max_length=10)),
                ('failure_reason', models.CharField(blank=True, choices=[('invalid_credentials', 'Invalid Username/Password'), ('account_locked', 'Account Locked'), ('account_disabled', 'Account Disabled'), ('ip_blocked', 'IP Address Blocked'), ('rate_limited', 'Rate Limited'), ('other', 'Other Reason')], help_text='Reason for failure (if applicable)', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User account (null if username not found)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_login_attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', 'timestamp'], name='auth_login__usernam_99e401_idx'), models.Index(fields=['ip_address', 'timestamp'], name='auth_login__ip_addr_fe98a7_idx'), models.Index(fields=['attempt_type', 'timestamp'], name='auth_login__attempt_2a2191_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(help_text='Hashed password', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_password_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='auth_passwo_user_id_fb4a85_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(help_text='Django session key', max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address')),
                ('user_agent', models.TextField(help_text='Client user agent string')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Session start time')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity time')),
                ('expires_at', models.DateTimeField(help_text='Session expiration time')),
                ('is_active', models.BooleanField(default=True, help_text='Is session currently active')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When session ended', null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('logout', 'User Logout'), ('timeout', 'Session Timeout'), ('admin_end', 'Ended by Administrator'), ('concurrent_limit', 'Concurrent Session Limit'), ('security_end', 'Security Policy')], help_text='Reason session ended', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='auth_user_s_user_id_e0ab05_idx'), models.Index(fields=['session_key'], name='auth_user_s_session_5780d2_idx'), models.Index(fields=['expires_at'], name='auth_user_s_expires_3df8ae_idx')],
            },
        ),
    ]
