# Generated by Django 5.2.1 on 2025-08-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_role_user_auditlog_loginattempt_passwordhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='session_key',
            field=models.CharField(blank=True, help_text='Session key if available', max_length=40, null=True),
        ),
    ]
